/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "lib/VirtualDrone/src/VDrone/nanopb/ahrs.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(AccelSample, AccelSample, AUTO)


PB_BIND(GyroSample, GyroSample, AUTO)


PB_BIND(MagSample, MagSample, AUTO)



