/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_LIB_VIRTUALDRONE_SRC_VDRONE_NANOPB_SIM_PB_H_INCLUDED
#define PB_LIB_VIRTUALDRONE_SRC_VDRONE_NANOPB_SIM_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _HeartBeat { 
    uint32_t timestamp; 
} HeartBeat;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define HeartBeat_init_default                   {0}
#define HeartBeat_init_zero                      {0}

/* Field tags (for use in manual encoding/decoding) */
#define HeartBeat_timestamp_tag                  1

/* Struct field encoding specification for nanopb */
#define HeartBeat_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   timestamp,         1)
#define HeartBeat_CALLBACK NULL
#define HeartBeat_DEFAULT NULL

extern const pb_msgdesc_t HeartBeat_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define HeartBeat_fields &HeartBeat_msg

/* Maximum encoded size of messages (where known) */
#define HeartBeat_size                           6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
